services:
  app:
    image: ghcr.io/${GHCR_OWNER}/acueducto-backend:latest
    container_name: acueducto-backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - mas-network

networks:
  mas-network:
    external: true
