services:
  app:
    image: ghcr.io/${GHCR_OWNER}/acueducto-backend:latest
    container_name: acueducto-backend
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - STORAGE_ENDPOINT=${STORAGE_ENDPOINT}
      - STORAGE_TENANT_ID=${STORAGE_TENANT_ID}
      - STORAGE_BUCKET=${STORAGE_BUCKET}
      - CONTABO_ACCESS_KEY=${CONTABO_ACCESS_KEY}
      - CONTABO_SECRET_KEY=${CONTABO_SECRET_KEY}
    networks:
      - mas-network

networks:
  mas-network:
    external: true
